fixtures:
  repositories:
    concat: 'git://github.com/puppetlabs/puppetlabs-concat.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  forge_modules:
    elrepo: "kemra102/elrepo"
  symlinks:
    drbd: "#{source_dir}"
